### ISSUE TITLE
Cannot Properly Register Bug - Invalid Token?

### ISSUE THREAD

**Issue by joatu** [joatuapp/joatu-v2#108]
User tried to create account with old token, succeeded to write password+postal code, came to this screen.  I created a +1 after her email and sent her another invitation.  Same error.  I deleted both users (the original and the plus 1), sent a fresh invite to her original email.  Same error.  I edited her user to give her a password, I tried logging in myself, same error.

![cannot login](https://cloud.githubusercontent.com/assets/5350076/6784997/5c39d10a-d159-11e4-8f11-b3dea0aab9a8.png)

She is using Safari.  I am using Chrome.

**Comment by joatu** [comment]
https://ghost.org/forum/bugs-suggestions/17670-some-email-s-activation-links-get-invalid-token/

http://stackoverflow.com/questions/22468308/devise-invitable-getting-invalid-token

**Comment by undergroundwebdesigns** [comment]
@joatu I am still not able to reproduce this (the email you used to reproduce it, as above, would help). I did find a hint at what might be the problem in another bug report on the Devise Invitable gem, and pushed that, but again, since I can't reproduce it, I can't be sure if that fixes it or not.

**Comment by undergroundwebdesigns** [comment]
Got an email address from @joatu and was able to reproduce this. Fixed, deploy happening as I type.
