### ISSUE TITLE
Bottom of page blurb does not mention GitHub

### ISSUE THREAD

**Issue by carlpaten** [joatuapp/joatu-v2#109]
> JoatU is 100% open source and is always looking for more help on all fronts!

Should have a GitHub mention, or preferably icon.

**Comment by joatu** [comment]
Clickable 'star' button instead of the link from 100% open source?  Where are the options in github to share this repo from other sites, I haven't found them yet.

**Comment by undergroundwebdesigns** [comment]
uh, why do we care? Github isn't a social network...

**Comment by joatu** [comment]
To be more attractive/standout to programmers.  Certain images grab attention.  A github icon that is familiar to programmers will grab more attention than a link hidden behind '100% open source'.

**Comment by lilred** [comment]
GitHub is DEFINITELY a social network :)
