### ISSUE TITLE
If no profile is created, there is no profile found when offer/request is clicked on.

### ISSUE THREAD

**Issue by joatu** [joatuapp/joatu-v2#111]
Can we add in the person's name when they put in their password so their profile is auto-created (even if there is nothing in the about section)?  One less step required for users would be nice.

I went to a new user's offer (who had not yet created their profile) : http://joatu.org/en/requests/47

I clicked on their profile and it brought me with this link to an error page that said this:

"The page you were looking for doesn't exist.

You may have mistyped the address or the page may have moved.

If you are the application owner check the logs for more information."

http://joatu.org/en/profiles/%23%3CAnonymousProfile:0x007f06b4f57410%3E

**Comment by joatu** [comment]
![image](https://user-images.githubusercontent.com/5350076/50253254-9bd77d00-03b7-11e9-9ba0-315c0cd375f9.png)

A simple solution could be having the first page displayed when they login for the first time as the 'profile creation' page and having it be required that they fill out something.

**Comment by rsmithlal** [comment]
This specific problem with the bad URL has been fixed. I also remove the link to the profile on the offer and request detail view. There is another issue that exists to have a profile created for them when they sign up, so I will close this one for now.

**Comment by joatu** [comment]
I would like to keep seeing the link to their profiles on the offer/request pages. And as of right now, it's still there, and when I clicked on it for Emmanuelle, it lead me to an error page.

The Offer: https://alpha.joatu.org/en/requests/125

When I click the profile name: https://alpha.joatu.org/en/profiles/65
 (We're sorry, but something went wrong.

If you are the application owner check the logs for more information.)

**Comment by rsmithlal** [comment]
When the user has a profile, the link is still there. Only when they haven't created a profile yet do I not render the link to the (non-existent) profile. The error you're encountering is another one, so good find. I will create an issue for it.

**Comment by joatu** [comment]
Great, ok.
