### ISSUE TITLE
Different font when page loads slowly

### ISSUE THREAD

**Issue by joatu** [joatuapp/joatu-v2#136]
This probably won't matter since we're looking to change the front page again anyhow, but I just found it odd. I don't believe that this shouldn't happen.

![slow load](https://cloud.githubusercontent.com/assets/5350076/7886653/7fba222c-05f9-11e5-8739-4e84f9ffd783.png)

**Comment by undergroundwebdesigns** [comment]
This isn't really a bug... we're using a custom font, which means it has to load. If the page is loading slowly, you _may_ see the page before the font loads, in which case this is going to happen. Not much we can specifically do about it, other than using a different font that is already included on people's computers, or speeding up pageloads in general.
