### ISSUE TITLE
Destroying requests/offers results in Error Page

### ISSUE THREAD

**Issue by joatu** [joatuapp/joatu-v2#145]
I created a new offer.

It was here: http://joatu.org/en/offers/97

I click 'destroy' and I am brought to this page: 

"We're sorry, but something went wrong.

If you are the application owner check the logs for more information."

Requests/Offers are however successfully destroyed.

**Comment by joatu** [comment]
![image](https://user-images.githubusercontent.com/5350076/49748846-ccf7d500-fc74-11e8-84b9-98bbfc12e22b.png)


Application Trace | Framework Trace | Full Trace
vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_dispatch/routing/polymorphic_routes.rb:220:in `polymorphic_method'
vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_dispatch/routing/polymorphic_routes.rb:114:in `polymorphic_url'
vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_dispatch/routing/url_for.rb:164:in `url_for'
vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_controller/metal/redirecting.rb:95:in `_compute_redirect_to_location'
vendor/bundle/ruby/2.4.0/gems/turbolinks-2.5.3/lib/turbolinks/xhr_headers.rb:21:in `_compute_redirect_to_location'
vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_controller/metal/redirecting.rb:75:in `redirect_to'
vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_controller/metal/flash.rb:57:in `redirect_to'
vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_controller/metal/instrumentation.rb:64:in `block in redirect_to'
vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/notifications.rb:164:in `block in instrument'
vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/notifications.rb:164:in `instrument'
vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_controller/metal/instrumentation.rb:63:in `redirect_to'
vendor/bundle/ruby/2.4.0/gems/responders-2.4.0/lib/action_controller/responder.rb:145:in `redirect_to'
vendor/bundle/ruby/2.4.0/gems/responders-2.4.0/lib/action_controller/responder.rb:205:in `navigation_behavior'
vendor/bundle/ruby/2.4.0/gems/responders-2.4.0/lib/action_controller/responder.rb:172:in `rescue in to_html'
vendor/bundle/ruby/2.4.0/gems/responders-2.4.0/lib/action_controller/responder.rb:169:in `to_html'
vendor/bundle/ruby/2.4.0/gems/responders-2.4.0/lib/action_controller/responder.rb:163:in `respond'
vendor/bundle/ruby/2.4.0/gems/responders-2.4.0/lib/action_controller/responder.rb:156:in `call'
vendor/bundle/ruby/2.4.0/gems/responders-2.4.0/lib/action_controller/respond_with.rb:211:in `respond_with'
app/controllers/offers_controller.rb:73:in `destroy'
vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/abstract_controller/base.rb:198:in `process_action'
vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_controller/metal/rendering.rb:10:in `process_action'
vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/callbacks.rb:117:in `call'
vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/callbacks.rb:505:in `call'
vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/callbacks.rb:81:in `run_callbacks'
vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/abstract_controller/callbacks.rb:19:in `process_action'
vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_controller/metal/rescue.rb:29:in `process_action'
vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/notifications.rb:164:in `block in instrument'
vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/notifications.rb:164:in `instrument'
vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/abstract_controller/base.rb:137:in `process'
vendor/bundle/ruby/2.4.0/gems/actionview-4.2.11/lib/action_view/rendering.rb:30:in `process'
vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_controller/metal.rb:196:in `dispatch'
vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_controller/metal.rb:237:in `block in action'
vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_dispatch/routing/route_set.rb:43:in `serve'
vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_dispatch/journey/router.rb:43:in `block in serve'
vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_dispatch/journey/router.rb:30:in `each'
vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_dispatch/journey/router.rb:30:in `serve'
vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_dispatch/routing/route_set.rb:817:in `call'
vendor/bundle/ruby/2.4.0/gems/skylight-core-3.1.2/lib/skylight/core/probes/action_dispatch/routing/route_set.rb:14:in `block in call'
vendor/bundle/ruby/2.4.0/gems/skylight-core-3.1.2/lib/skylight/core/fanout.rb:25:in `instrument'
vendor/bundle/ruby/2.4.0/gems/skylight-core-3.1.2/lib/skylight/core/probes/action_dispatch/routing/route_set.rb:13:in `call'
vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-5.5.0.348/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-5.5.0.348/lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-5.5.0.348/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
vendor/bundle/ruby/2.4.0/gems/skylight-core-3.1.2/lib/skylight/core/probes/middleware.rb:26:in `call'
vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-5.5.0.348/lib/new_relic/rack/browser_monitoring.rb:32:in `traced_call'
vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-5.5.0.348/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
vendor/bundle/ruby/2.4.0/gems/skylight-core-3.1.2/lib/skylight/core/probes/middleware.rb:26:in `call'
vendor/bundle/ruby/2.4.0/gems/warden-1.2.7/lib/warden/manager.rb:36:in `block in call'
vendor/bundle/ruby/2.4.0/gems/warden-1.2.7/lib/warden/manager.rb:35:in `catch'
vendor/bundle/ruby/2.4.0/gems/warden-1.2.7/lib/warden/manager.rb:35:in `call'
vendor/bundle/ruby/2.4.0/gems/skylight-core-3.1.2/lib/skylight/core/probes/middleware.rb:26:in `call'
vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-5.5.0.348/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
vendor/bundle/ruby/2.4.0/gems/rack-1.6.11/lib/rack/etag.rb:24:in `call'
vendor/bundle/ruby/2.4.0/gems/skylight-core-3.1.2/lib/skylight/core/probes/middleware.rb:26:in `call'
vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-5.5.0.348/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
vendor/bundle/ruby/2.4.0/gems/rack-1.6.11/lib/rack/conditionalget.rb:38:in `call'
vendor/bundle/ruby/2.4.0/gems/skylight-core-3.1.2/lib/skylight/core/probes/middleware.rb:26:in `call'
vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-5.5.0.348/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
vendor/bundle/ruby/2.4.0/gems/rack-1.6.11/lib/rack/head.rb:13:in `call'
vendor/bundle/ruby/2.4.0/gems/skylight-core-3.1.2/lib/skylight/core/probes/middleware.rb:26:in `call'
vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-5.5.0.348/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
vendor/bundle/ruby/2.4.0/gems/skylight-core-3.1.2/lib/skylight/core/probes/middleware.rb:26:in `call'
vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-5.5.0.348/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_dispatch/middleware/flash.rb:260:in `call'
vendor/bundle/ruby/2.4.0/gems/skylight-core-3.1.2/lib/skylight/core/probes/middleware.rb:26:in `call'
vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-5.5.0.348/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
vendor/bundle/ruby/2.4.0/gems/rack-1.6.11/lib/rack/session/abstract/id.rb:225:in `context'
vendor/bundle/ruby/2.4.0/gems/rack-1.6.11/lib/rack/session/abstract/id.rb:220:in `call'
vendor/bundle/ruby/2.4.0/gems/skylight-core-3.1.2/lib/skylight/core/probes/middleware.rb:26:in `call'
vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-5.5.0.348/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_dispatch/middleware/cookies.rb:560:in `call'
vendor/bundle/ruby/2.4.0/gems/skylight-core-3.1.2/lib/skylight/core/probes/middleware.rb:26:in `call'
vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-5.5.0.348/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11/lib/active_record/query_cache.rb:36:in `call'
vendor/bundle/ruby/2.4.0/gems/skylight-core-3.1.2/lib/skylight/core/probes/middleware.rb:26:in `call'
vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-5.5.0.348/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
vendor/bundle/ruby/2.4.0/gems/skylight-core-3.1.2/lib/skylight/core/probes/middleware.rb:26:in `call'
vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-5.5.0.348/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/callbacks.rb:81:in `run_callbacks'
vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
vendor/bundle/ruby/2.4.0/gems/skylight-core-3.1.2/lib/skylight/core/probes/middleware.rb:26:in `call'
vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-5.5.0.348/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
vendor/bundle/ruby/2.4.0/gems/skylight-core-3.1.2/lib/skylight/core/probes/middleware.rb:26:in `call'
vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-5.5.0.348/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
vendor/bundle/ruby/2.4.0/gems/skylight-core-3.1.2/lib/skylight/core/probes/middleware.rb:26:in `call'
vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-5.5.0.348/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
vendor/bundle/ruby/2.4.0/gems/skylight-core-3.1.2/lib/skylight/core/probes/middleware.rb:26:in `call'
vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-5.5.0.348/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
vendor/bundle/ruby/2.4.0/gems/railties-4.2.11/lib/rails/rack/logger.rb:38:in `call_app'
vendor/bundle/ruby/2.4.0/gems/railties-4.2.11/lib/rails/rack/logger.rb:20:in `block in call'
vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/tagged_logging.rb:68:in `block in tagged'
vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/tagged_logging.rb:26:in `tagged'
vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/tagged_logging.rb:68:in `tagged'
vendor/bundle/ruby/2.4.0/gems/railties-4.2.11/lib/rails/rack/logger.rb:20:in `call'
vendor/bundle/ruby/2.4.0/gems/skylight-core-3.1.2/lib/skylight/core/probes/middleware.rb:26:in `call'
vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-5.5.0.348/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_dispatch/middleware/request_id.rb:21:in `call'
vendor/bundle/ruby/2.4.0/gems/skylight-core-3.1.2/lib/skylight/core/probes/action_dispatch/request_id.rb:12:in `call'
vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-5.5.0.348/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
vendor/bundle/ruby/2.4.0/gems/rack-1.6.11/lib/rack/methodoverride.rb:22:in `call'
vendor/bundle/ruby/2.4.0/gems/skylight-core-3.1.2/lib/skylight/core/probes/middleware.rb:26:in `call'
vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-5.5.0.348/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
vendor/bundle/ruby/2.4.0/gems/rack-1.6.11/lib/rack/runtime.rb:18:in `call'
vendor/bundle/ruby/2.4.0/gems/skylight-core-3.1.2/lib/skylight/core/probes/middleware.rb:26:in `call'
vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-5.5.0.348/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_dispatch/middleware/static.rb:120:in `call'
vendor/bundle/ruby/2.4.0/gems/skylight-core-3.1.2/lib/skylight/core/probes/middleware.rb:26:in `call'
vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-5.5.0.348/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
vendor/bundle/ruby/2.4.0/gems/rack-1.6.11/lib/rack/sendfile.rb:113:in `call'
vendor/bundle/ruby/2.4.0/gems/skylight-core-3.1.2/lib/skylight/core/probes/middleware.rb:26:in `call'
vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-5.5.0.348/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
vendor/bundle/ruby/2.4.0/gems/railties-4.2.11/lib/rails/engine.rb:518:in `call'
vendor/bundle/ruby/2.4.0/gems/railties-4.2.11/lib/rails/application.rb:165:in `call'
vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-5.5.0.348/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
vendor/bundle/ruby/2.4.0/gems/puma-3.12.0/lib/puma/configuration.rb:225:in `call'
vendor/bundle/ruby/2.4.0/gems/puma-3.12.0/lib/puma/server.rb:658:in `handle_request'
vendor/bundle/ruby/2.4.0/gems/puma-3.12.0/lib/puma/server.rb:472:in `process_client'
vendor/bundle/ruby/2.4.0/gems/puma-3.12.0/lib/puma/server.rb:332:in `block in run'
vendor/bundle/ruby/2.4.0/gems/puma-3.12.0/lib/puma/thread_pool.rb:133:in `block in spawn_thread'

Request
Parameters:

{"_method"=>"delete",
 "authenticity_token"=>"T1ZDF7o3z0VGjyazLp0klHPMmlTz5hu85jed00feCfuIbFE/aeEgbIt24NToKbhWiWUlUEMcIXdtsnBjzGdSSA==",
 "locale"=>"en",
 "id"=>"126"}

Toggle session dump
_csrf_token: "xzoSKNPW7ynN+cZnxrScwvqpvwSw+jrLi4XtsIu5W7M="
session_id: "cb3a6d67917b156598aedd38049a20c5"
warden.user.user.key: [[2], "$2a$10$z4UNIXcG4HowBxdm28RJB."]
Toggle env dump
GATEWAY_INTERFACE: "CGI/1.2"
HTTP_ACCEPT: "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8"
HTTP_ACCEPT_ENCODING: "gzip, deflate"
HTTP_ACCEPT_LANGUAGE: "en-GB,en-US;q=0.9,en;q=0.8"
HTTP_CACHE_CONTROL: "max-age=0"
REMOTE_ADDR: "10.47.234.240"
SERVER_NAME: "alpha.joatu.org"
SERVER_PROTOCOL: "HTTP/1.1"
Response
Headers:

None

**Comment by rsmithlal** [comment]
I think I have some work to do to refactor the offers and requests code. They seem to be sharing the same database table and there is some awkward setup there.

Cheers,
Rob

**Comment by rsmithlal** [comment]
Fixed as part of #170

**Comment by rsmithlal** [comment]
This has now been resolved. Please test in the alpha app and confirm.

**Comment by joatu** [comment]
Resolved!
