### ISSUE TITLE
Can't create offer or request

### ISSUE THREAD

**Issue by elmimz** [joatuapp/joatu-v2#146]
Preconditions:
User is logged in to joatu

Procedure:
User attempts to create an offer (or request) by filling all fields with valid data

Expected behaviour:
Offer (or request) created and published

Actual behaviour:
Offer/Request not created:

User is redirected to a new page:
"we're sorry something went wrong. 
If you are the application owner check the logs for more information."

**Comment by joatu** [comment]
Cannot reproduce as admin.
Cannot reproduce as regular user part of NDG pod.
http://alpha.joatu.org/en/offers/98

What pod are you a part of?

**Comment by elmimz** [comment]
It seems that this is the problem :) I don't have a pod for my postal code. 

Issue updated.
