### ISSUE TITLE
Add Profile References

### ISSUE THREAD

**Issue by undergroundwebdesigns** [joatuapp/joatu-v2#15]
# Goal
Members should be able to leave references on other members' profiles, so that the JoatU community can have confidence in the identity and character of it's members.

## Questions:
attn: @joatu:
- How should references be "rated"?
  - positive, neutral, negative?
  - 1 through 5, or 5 stars?
  - other?

## To build:
- [ ] Create Reference resource, which has a reference (text) and rating
- [ ] A member can leave a single reference on any other member's profile.
- [ ] A member can edit their reference.
- [ ] A member can remove their reference.
- [ ] Reciprocal references are displayed together.

**Comment by joatu** [comment]
- [ ] 1-5 star rating
- [ ] Include a text explanation
- [ ] Have a dropdown menu to allow the reference writer the opportunity to select which offer the reference is pertaining to (and display the title on the reference itself) and include 'general' for general references

**Comment by undergroundwebdesigns** [comment]
Sounds good. You've given me enough to get started with, but here are some other questions / thoughts:
- If we're letting people write references associated with a specific offer, how do we want to handle it if the user removes that offer? Do the references go away too? Do we indicate that it was for a removed offer?
- Would we show the "offer references" on the profile page? On the specific offer page? Both places?

**Comment by joatu** [comment]
Keep the title of the offer in the reference and change nothing if they decide to change/remove the offer.  

If they edit their offer, each new reference will have a different title. That's ok (I think).  For simplicity, we can list all references together and give an average of the star ratings on the top of the page. Maybe we should prepare to be able to change that at some point, but in the early days it seems overzealous and unnecessary to make things separate.
