### ISSUE TITLE
Clicked on caps generator, brought up error screen.

### ISSUE THREAD

**Issue by joatu** [joatuapp/joatu-v2#156]
Clicked on caps generator, brought up error screen.

NoMethodError in Admin::CapsController#new

undefined method `_read_attribute' for #<CapsGenerator:0x00007f0ee49aa610>

Extracted source (around line #10):

8 9 10 11 12 13 

@users = User.all 

@organizations = Organization.all 

@form = CapsTransactionForm.new(CapsTransaction.new(source: CapsGenerator.instance)) 

authorize @form.model 

respond_with(@caps_transaction = @form) 

end 

Rails.root: /app

Application Trace | Framework Trace | Full Trace

app/controllers/admin/caps_controller.rb:10:in `new'

Request

Parameters:

{"locale"=>"en"}

Toggle session dump

_csrf_token: "LIN3BclRZY90oA7b2BSSitBQ2kWhNmy9MmEYJ4j9Cb0=" session_id: "c0200c8b572b2b206febcfa2d207a002" warden.user.user.key: [[2], "$2a$10$z4UNIXcG4HowBxdm28RJB."]

Toggle env dump

GATEWAY_INTERFACE: "CGI/1.2" HTTP_ACCEPT: "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8" HTTP_ACCEPT_ENCODING: "gzip, deflate" HTTP_ACCEPT_LANGUAGE: "en-CA,en-GB;q=0.9,en-US;q=0.8,en;q=0.7" HTTP_CACHE_CONTROL: "no-cache" HTTP_PRAGMA: "no-cache" REMOTE_ADDR: "10.159.208.89" SERVER_NAME: "alpha.joatu.org" SERVER_PROTOCOL: "HTTP/1.1"

Response

Headers:

None

**Comment by rsmithlal** [comment]
Thanks, I'll take a look at that one soon! Do you actually use the caps for
anything at the moment?

**Comment by joatu** [comment]
Nope!

**Comment by rsmithlal** [comment]
This should be resolved now. Please test and close

**Comment by rsmithlal** [comment]
Sorry, just realized that I forgot to deploy the changes for this fix. Should work now!

**Comment by joatu** [comment]
Fixed!
