### ISSUE TITLE
New User cannot create password; therefore cannot join

### ISSUE THREAD

**Issue by joatu** [joatuapp/joatu-v2#157]
I invited a new user and put in a password several times, hit enter, then it keeps says that the Password "can't be blank" even though it wasn't.

![image](https://user-images.githubusercontent.com/5350076/49749245-c4ec6500-fc75-11e8-9225-ecfb84e95765.png)

**Comment by joatu** [comment]
Tested on both firefox and chrome.

**Comment by rsmithlal** [comment]
Seems to be an issue with the changes for the new version of the devise login gem. I will take a look at it soon. 

Cheers,
Rob

From: joatu
Sent: December 10, 2018 12:19 PM
To: joatuapp/joatu-v2
Cc: Subscribed
Subject: [joatuapp/joatu-v2] New User cannot create password; therefore cannotjoin (#157)

I invited a new user and put in a password several times, hit enter, then it keeps says that the Password "can't be blank" even though it wasn't.
