### ISSUE TITLE
After last bug reported, whole site crashed

### ISSUE THREAD

**Issue by joatu** [joatuapp/joatu-v2#166]
![image](https://user-images.githubusercontent.com/5350076/50249012-dc7cc980-03aa-11e9-91da-59f836143be2.png)

649 650 651 652 653 654 | # connected server's characteristics.         def connect           @connection = PGconn.connect(@connection_parameters)            # Money type has a fixed precision of 10 in PostgreSQL 8.2 and below, and as of           # PostgreSQL 8.3 it has a fixed precision of 19. PostgreSQLColumn.extract_precision
-- | --

Rails.root: /app

Application Trace | Framework Trace | Full Trace
vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in `initialize'
vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in `new'
vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in `connect'
vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11/lib/active_record/connection_adapters/postgresql_adapter.rb:242:in `initialize'
vendor/bundle/ruby/2.4.0/gems/activerecord-postgis-adapter-3.0.0.beta1/lib/active_record/connection_adapters/postgis_adapter/main_adapter.rb:23:in `initialize'
vendor/bundle/ruby/2.4.0/gems/activerecord-postgis-adapter-3.0.0.beta1/lib/active_record/connection_adapters/postgis_adapter/create_connection.rb:38:in `new'
vendor/bundle/ruby/2.4.0/gems/activerecord-postgis-adapter-3.0.0.beta1/lib/active_record/connection_adapters/postgis_adapter/create_connection.rb:38:in `postgis_connection'
vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11/lib/active_record/connection_adapters/abstract/connection_pool.rb:438:in `new_connection'
vendor/bundle/ruby/2.4.0/gems/rgeo-activerecord-2.1.0/lib/rgeo/active_record/ar_factory_settings.rb:135:in `new_connection'
vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11/lib/active_record/connection_adapters/abstract/connection_pool.rb:448:in `checkout_new_connection'
vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11/lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'
vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
vendor/ruby-2.4.5/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
vendor/ruby-2.4.5/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11/lib/active_record/connection_adapters/abstract/connection_pool.rb:571:in `retrieve_connection'
vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11/lib/active_record/connection_handling.rb:87:in `connection'
vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11/lib/active_record/query_cache.rb:51:in `restore_query_cache_settings'
vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11/lib/active_record/query_cache.rb:43:in `rescue in call'
vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11/lib/active_record/query_cache.rb:30:in `call'
vendor/bundle/ruby/2.4.0/gems/skylight-core-3.1.2/lib/skylight/core/probes/middleware.rb:34:in `call'
vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-5.5.0.348/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
vendor/bundle/ruby/2.4.0/gems/skylight-core-3.1.2/lib/skylight/core/probes/middleware.rb:34:in `call'
vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-5.5.0.348/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/callbacks.rb:81:in `run_callbacks'
vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
vendor/bundle/ruby/2.4.0/gems/skylight-core-3.1.2/lib/skylight/core/probes/middleware.rb:34:in `call'
vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-5.5.0.348/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
vendor/bundle/ruby/2.4.0/gems/skylight-core-3.1.2/lib/skylight/core/probes/middleware.rb:34:in `call'
vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-5.5.0.348/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
vendor/bundle/ruby/2.4.0/gems/skylight-core-3.1.2/lib/skylight/core/probes/middleware.rb:34:in `call'
vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-5.5.0.348/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
vendor/bundle/ruby/2.4.0/gems/skylight-core-3.1.2/lib/skylight/core/probes/middleware.rb:34:in `call'
vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-5.5.0.348/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
vendor/bundle/ruby/2.4.0/gems/railties-4.2.11/lib/rails/rack/logger.rb:38:in `call_app'
vendor/bundle/ruby/2.4.0/gems/railties-4.2.11/lib/rails/rack/logger.rb:20:in `block in call'
vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/tagged_logging.rb:68:in `block in tagged'
vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/tagged_logging.rb:26:in `tagged'
vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/tagged_logging.rb:68:in `tagged'
vendor/bundle/ruby/2.4.0/gems/railties-4.2.11/lib/rails/rack/logger.rb:20:in `call'
vendor/bundle/ruby/2.4.0/gems/skylight-core-3.1.2/lib/skylight/core/probes/middleware.rb:34:in `call'
vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-5.5.0.348/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_dispatch/middleware/request_id.rb:21:in `call'
vendor/bundle/ruby/2.4.0/gems/skylight-core-3.1.2/lib/skylight/core/probes/action_dispatch/request_id.rb:12:in `call'
vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-5.5.0.348/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
vendor/bundle/ruby/2.4.0/gems/rack-1.6.11/lib/rack/methodoverride.rb:22:in `call'
vendor/bundle/ruby/2.4.0/gems/skylight-core-3.1.2/lib/skylight/core/probes/middleware.rb:34:in `call'
vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-5.5.0.348/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
vendor/bundle/ruby/2.4.0/gems/rack-1.6.11/lib/rack/runtime.rb:18:in `call'
vendor/bundle/ruby/2.4.0/gems/skylight-core-3.1.2/lib/skylight/core/probes/middleware.rb:34:in `call'
vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-5.5.0.348/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_dispatch/middleware/static.rb:120:in `call'
vendor/bundle/ruby/2.4.0/gems/skylight-core-3.1.2/lib/skylight/core/probes/middleware.rb:34:in `call'
vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-5.5.0.348/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
vendor/bundle/ruby/2.4.0/gems/rack-1.6.11/lib/rack/sendfile.rb:113:in `call'
vendor/bundle/ruby/2.4.0/gems/skylight-core-3.1.2/lib/skylight/core/probes/middleware.rb:34:in `call'
vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-5.5.0.348/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
vendor/bundle/ruby/2.4.0/gems/skylight-core-3.1.2/lib/skylight/core/middleware.rb:83:in `call'
vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-5.5.0.348/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
vendor/bundle/ruby/2.4.0/gems/railties-4.2.11/lib/rails/engine.rb:518:in `call'
vendor/bundle/ruby/2.4.0/gems/railties-4.2.11/lib/rails/application.rb:165:in `call'
vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-5.5.0.348/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
vendor/bundle/ruby/2.4.0/gems/puma-3.12.0/lib/puma/configuration.rb:225:in `call'
vendor/bundle/ruby/2.4.0/gems/puma-3.12.0/lib/puma/server.rb:658:in `handle_request'
vendor/bundle/ruby/2.4.0/gems/puma-3.12.0/lib/puma/server.rb:472:in `process_client'
vendor/bundle/ruby/2.4.0/gems/puma-3.12.0/lib/puma/server.rb:332:in `block in run'
vendor/bundle/ruby/2.4.0/gems/puma-3.12.0/lib/puma/thread_pool.rb:133:in `block in spawn_thread'

**Comment by rsmithlal** [comment]
Seems like a network glitch of some kind, will close for now but let me know if it happens again
