### ISSUE TITLE
Mobile Optimisation - Update Twitter Bootstrap

### ISSUE THREAD

**Issue by joatu** [joatuapp/joatu-v2#168]
If I'm not mistaken, the mobile environment was a lot more user-friendly before the list of updates started coming along. I believe this has to do with Twitter Bootstrap, and I believe it might not be integrated in the same way that it was before.

Perhaps once Twitter Bootstrap is back working properly, further optimisation could be put on the backburner.

**Comment by joatu** [comment]
I'd add this into priorities of bugs before we bring new folks in.

**Comment by joatu** [comment]
I'll try to find you some screenshots. Basically, the site shrunk down to
the size of the screen. So the text got bigger and you only saw so many
things at once. Especially for offers/requests/messages.

**Comment by joatu** [comment]
Depending on the size of the screen, you would see it differently.
![offers](https://user-images.githubusercontent.com/5350076/51807453-f8e70e00-2254-11e9-8fa2-5ef4301cfe0d.png)
![requests](https://user-images.githubusercontent.com/5350076/51807455-fab0d180-2254-11e9-9ec0-31df8f6fff54.png)

**Comment by joatu** [comment]
I just tested this issue and **it is a problem with Google Chrome on Mobile**. 
It is not an issue with Google Chrome on PC. 
It is not an issue with Firefox on PC or Mobile.

**Comment by rsmithlal** [comment]
That's interesting, because I was finding that the responsive layout behaved as expected in Chrome on desktop when resizing the browser window, but as soon as I turned on mobile device emulation it stopped working. This is a very helpful finding, as it will help narrow down the search for a solution.

**Comment by rsmithlal** [comment]
I'm going to leave this in a comment for later. It seems like this could be responsible for the issues that we're seeing: https://www.w3schools.com/css/css_rwd_viewport.asp

**Comment by rsmithlal** [comment]
This should be finished now. Please test and confirm.
