### ISSUE TITLE
Map doesn't always show when loaded in Chrome

### ISSUE THREAD

**Issue by joatu** [joatuapp/joatu-v2#175]
![image](https://user-images.githubusercontent.com/5350076/54883101-235ddd80-4e38-11e9-8bf7-2e0ebf9086eb.png)

I've noticed it more than once that when I load JoatU for the first time, the map does not display.

To resolve this issue, I can click on the 'offers' or 'requests' then on the Joatu link and the map will render afterwards.

**Comment by rsmithlal** [comment]
This is fixed as part of #170

**Comment by rsmithlal** [comment]
This has now been resolved. Please test in the alpha app and confirm.
