### ISSUE TITLE
No Emails are going out whatsoever (Rails 5)

### ISSUE THREAD

**Issue by joatu** [joatuapp/joatu-v2#186]
#170 

I cannot create new users by invitation or in the backend (because they need to verify their email address). Therefore, I cannot test any email-related notifications (such as conversations). This may be because of sendgrid (which will hopefully resolve itself within 72 hours).

**Comment by rsmithlal** [comment]
What exactly did you do that would potentially resolve it in 72h?

**Comment by joatu** [comment]
Sendgrid may reactivate the account, that's all.

**Comment by rsmithlal** [comment]
Okay, thanks. Hopefully they let us send emails from the test app, but if
not I will configure the test apps to use something else if I can. Doesn't
need full email tracking, just needs to send mail.

**Comment by rsmithlal** [comment]
The alpha app is now running on rails 5, so please test this in the alpha app and confirm that things are ok.

**Comment by joatu** [comment]
Cannot test until #196 (conversations not working) is resolved.

**Comment by rsmithlal** [comment]
Try inviting a new user

**Comment by joatu** [comment]
Oh, yes. That works. I successfully invited myself.

**Comment by rsmithlal** [comment]
Since the emails do work in general, I will close this. Will address #196 in its own issue.
