### ISSUE TITLE
Creating Profile sends to dead end error

### ISSUE THREAD

**Issue by joatu** [joatuapp/joatu-v2#302]
![image](https://user-images.githubusercontent.com/5350076/81366932-5ebe7880-90db-11ea-9428-166b6e856cc4.png)

After signup, clicking the nice confirmation email, I started filling out my profile, and then when I clicked to submit, it redirected me to this error page.

And this was the link: https://alpha.joatu.org/en/profiles

**Comment by rsmithlal** [comment]
This has been resolved
