### ISSUE TITLE
Add "please check your spam folder for confirmation email" to sign up page

### ISSUE THREAD

**Issue by joatu** [joatuapp/joatu-v2#319]
Add "please check your spam folder for confirmation email" to sign up page until the spam issue is resolved.

**Comment by rsmithlal** [comment]
Is there any text on or around the form now that you could modify to include this message?

**Comment by joatu** [comment]
I'm sure there is. Do you know offhand where the form (or page) is located?

**Comment by rsmithlal** [comment]
It's under the devise directory of the views folder I think. Should be under registrations/new. You can also search the project for the text in the English locales file and go in and change the text there. If you need to add a new text area you can do it in the HTML view mentioned above, but shouldn't need to tough the HTML if there is already a text there that you can append your message to.

**Comment by joatu** [comment]
I can append it to the 'terms of use' text in the EN file. I'll modify that and see if it works.

[ ] I agree to check my spam folder for my confirmation email and to the terms of use 

![image](https://user-images.githubusercontent.com/5350076/82841790-d73c7c00-9ec6-11ea-8576-dc1343c8766e.png)

**Comment by rsmithlal** [comment]
Do it in a new branch (or create a new branch with your change in the github interface) and create a pull request for the branch into master. That should trigger a review app deployment for the branch that you can use to confirm and test your changes

**Comment by joatu** [comment]
I've modified the en one, I'm just getting a friend to do a better french translation for me before I change the fr one too and try to merge.

**Comment by joatu** [comment]
Is this safe?  @rsmithlal 
![image](https://user-images.githubusercontent.com/5350076/82853355-17b2ee80-9ef5-11ea-912f-eab0aec3b633.png)
