### ISSUE TITLE
No Live linking email addresses

### ISSUE THREAD

**Issue by joatu** [joatuapp/joatu-v2#35]
Live linking email addresses on the web these days? No thank you. Let the contact section have some weird symbols for the @ sign or something like that please.

**Comment by undergroundwebdesigns** [comment]
In all honesty, there's absolutely nothing I can come up with that the bots can't (and won't) understand. It's all dead and gone. There's one way and only one way to stop spam: get a good spam filter. This is why everyone uses Gmail... they have one of the best spam filters, and it's built right in. If you're really that concerned about protecting your email, we have to not post it at all, and replace it with a separate page with a contact form. Which we can do, but it takes time. And it's not important enough for me to rush.

Further reference about the irrelevance of "protecting" your email this way: http://www.loopinsight.com/2014/03/02/theres-really-no-need-to-conceal-your-email-address-from-spammers/. Google has more.

**Comment by joatu** [comment]
Understood.
