### ISSUE TITLE
Follow Us (in Footer)

### ISSUE THREAD

**Issue by joatu** [joatuapp/joatu-v2#37]
No links to FB, Twitter, Tumblr, LinkedIn or any of the others posted there currently.

**Comment by undergroundwebdesigns** [comment]
What should the links point to? Which of those accounts do you have for JoatU, and what are the URLs?

**Comment by joatu** [comment]
FB: https://www.facebook.com/joatunit
Twitter: https://twitter.com/Joatunit
Instagram:  http://instagram.com/joatu_
Tumblr: http://joatu.tumblr.com/
G+ : https://plus.google.com/+Joatuniverse/posts
LinkedIn: https://www.linkedin.com/company/joatu
