### ISSUE TITLE
Add Terms of Agreement to Registration

### ISSUE THREAD

**Issue by joatu** [joatuapp/joatu-v2#38]
- [ ] create / acquire ToA and post them as a comment on this ticket
- [ ] add a page for the terms of agreement
- [ ] add a checkbox in the registration that must be checked off for registration
- [ ] check off this box

**Comment by undergroundwebdesigns** [comment]
@joatu assigned you. No sense adding an empty page, if you get me some ToA text, I'll post it. Ideally translated to both languages.

**Comment by joatu** [comment]
We have the text in English. I'll email it to you. For legal reasons, let's have the English text on both the French and English sites. Unfortunately, having a legal text translated has ramifications that risk invalidating or contradicting the original text.

**Comment by undergroundwebdesigns** [comment]
I've seen translations where there was a prominent line basically saying "in case of disagreement between this and the english version, the english shall be taken as valid". Something to consider. For now I'll go forward with just English.

**Comment by joatu** [comment]
Ah, interesting and good. I'll keep that in mind for sure.
