### ISSUE TITLE
Design Requests

### ISSUE THREAD

**Issue by joatu** [joatuapp/joatu-v2#41]
- [x] Have 'How it Works' as the first listed in the header
- [x] Have 'How it works' as the first section after the main home (before features or benefits)
- [x] Consider changing the text on the very first page to "A hyper-local marketplace for skills and resources in your community!" (if you do think that's best, take the text "Trade your skills and goods, meet your needs and create vibrant communities!" and place it as a subheader in the Benefits section)
- [x] Replace 'How it works' text that reads "Understand JoatU Better!" with "Welcome to the Jack of all trades Universe!"
- [x] In Benefits, replace text "Offer your skills and be rewarded" with "Help others and be helped"
- [x] In Benefits, switch the places of "Hyperlocal Resource Directory" and "Build bonds with your neighbors" so that the build bonds is the 1st category and the hyperlocal is the 2nd.
- [x] Consider making the footer the color of the inside of the lime: https://hothousebotanicals.files.wordpress.com/2008/10/lime-photo.jpg
- [x] In Footer: Replace the Join Us section with "Join Us (next line) JoatU is 100% open source (linking to github) and is always looking for more help on all fronts!" (no need to include email link here)

MOAR

- [x] Add Sub-headline to Benefits section "Join your hyperlocal marketplace for skills and goods"
- [x] Different shadings between pages/sections

**Comment by joatu** [comment]
Changed Tag line to : "Trade skills and goods to meet your needs, and create vibrant communities!"

**Comment by joatu** [comment]
Need translation for "Join your hyperlocal marketplace for skills and goods" also please.

**Comment by fredofromstart** [comment]
Voici-voilà !

Trade skills and goods to meet your needs, and create vibrant communities!
 ==> 
Échangez biens et services pour répondre à vos besoins et créer de vibrantes communautés !

JoatU is 100% open source (linking to github) and is always looking for more help on all fronts! 
==> 
JoatU est 100 % « open source » et est toujours à l'affût de coups de main supplémentaires sur tous les fronts !

Join your hyperlocal marketplace for skills and goods 
==> 
Rejoignez votre marché hyperlocal de biens et services

Welcome to the Jack of all trades Universe! 
==> 
Bienvenue sur JoatU (Jack of all trades Universe) !

Help others and be helped 
==> 
Donnez et recevez de l'aide
