### ISSUE TITLE
First Image doesn't take up full screen in higher resolutions

### ISSUE THREAD

**Issue by joatu** [joatuapp/joatu-v2#42]
16:10
1680 x 1050

![10967118_10155258426280643_940550071_o](https://cloud.githubusercontent.com/assets/5350076/5990810/7ad37452-a992-11e4-8504-a7178c3b5dbb.jpg)

1920x1080
![1920x1080](https://cloud.githubusercontent.com/assets/5350076/5990812/b87917ee-a992-11e4-80df-bed3f2147e40.png)

**Comment by undergroundwebdesigns** [comment]
fixed.
