### ISSUE TITLE
Support Us - In Footer

### ISSUE THREAD

**Issue by joatu** [joatuapp/joatu-v2#43]
After 'Mail Us' there's a nice blank space.  Let's put this there please. If you have a better wording suggestion, I'm open.

Support us with Bitcoin
1335KiPa82fkgESyNVy7nA74W4vyQjUpwY

**Comment by undergroundwebdesigns** [comment]
Can we get "Support us with Bitcoin" and "Wallet: <wallet_id_will_go_here>" translated to french please? @joatu ?

**Comment by joatu** [comment]
Wallet = Portefeuille
Support us with Bitcoin = Encouragez-nous avec Bitcoin !
