### ISSUE TITLE
Dynamically segment Mailchimp list "JoatU Alpha Preregistration" by geolocation.

### ISSUE THREAD

**Issue by joatu** [joatuapp/joatu-v2#44]
We'll have a lot of emails and a lot of postal codes.  How can we track to see where they all are without having to do a ton of manual work?

**Comment by undergroundwebdesigns** [comment]
We can (and will) write a tool that will be able to grab this information (email addresses and postal codes), look up more information about the postal codes, and then feed back into the list, allowing us to group people pretty much however we want. City, neighbourhood, and of course by postal code itself should all be possible, especially for North American cities (quality of publicly available Geo information for North America is quite a bit better than for the rest of the world).
