### ISSUE TITLE
Translation Requests

### ISSUE THREAD

**Issue by joatu** [joatuapp/joatu-v2#45]
- [x] I looked at the welcome page and everything seems alright. Maybe we should just capitalize « points d'ACC » this way. 

- [ ] Also, when I asked for an invitation, I had a non-translated message : "Almost finished... We need to confirm...".
Oh, and also : the email mesage I received to confirm my email address is all in English.

- [x] Oh, and the punctuation under the Features You'll Love section is inconsistent (both in English and French). A few periods are missing

- [x]  I would remove "Regardez notre" and keep only "Animation de présentation". It sounds a little too "insistent" to me. ^^

- [x] I would invert "Inscrivez-vous à notre bulletin d'information" and "Restez informé(e) !".

**Comment by undergroundwebdesigns** [comment]
Unfortunately we don't have as much control over the language used in the "confirm your email" emails. However, they will try to autodetect which language to use based on your browser / computer settings, so if you had your computer OS set to French, it would probably have sent them in french. I just checked and there doesn't seem to be an easy way to prompt it :(.
