### ISSUE TITLE
Logged In Page

### ISSUE THREAD

**Issue by joatu** [joatuapp/joatu-v2#54]
Each Joatu Pod should have a separate logged in page.

A map should be displayed showing all of the users within the area with the Pod clearly identified. All of the points on the map showing users should be 100% anonymous and not be linked to their profiles.

If we are afraid for privacy issues, we can avoid placing people on the map but geo-locate their distances from one another based on their postal codes (this is actually ideal and would give us a very valuable search parameter for the future when we extend to include other pods in our search parameters for those willing to travel further).

Alongside the map should be a short written piece about the JoatU Hub featured for this specific JoatU Pod along with the hours of operation.  We should include a picture or a video and brief directions as well.  It should also be clearly outlined what the purpose of the JoatU Hub is.

Local (Free) Events should also be displayed next to that. For the meantime, that could be maintained by admin but eventually we can allow for submissions (and also through community offers).

If people propose community offers at a hub, that should mean that the Hub itself should have a JoatU account to confirm the possibility of hosting the proposed event. In which case, the creation of the community offers happening at the hub becomes delegated to the Hub owners/directors.

Everyone should have a main JoatU Pod.  You should be able to select multiple pods later on (potentially as a premium feature).

JoatU Pod = Physical area on a map that limits the distance of users so that everyone is within a certain distance of one-another and of the JoatU Hub.

JoatU Hub = A central location within the JoatU Pod that is non-commercial and can be seen as a neutral meeting point that is convenient for all parties. For our first Pod, the hub will be located at a maximum distance of a 20 minute walk from the furthest members. Ideally, if we have enough members, we only include members that are a 10 minute walk from the hub, making everyone within Pod 1 a maximum distance of a 20 minute walk from each other.

**Comment by undergroundwebdesigns** [comment]
Closing this, as I've copied the text to a Milestone here: https://github.com/joatuapp/joatu-v2/milestones/JoatU%20Pods. We're going to need multiple issues to tackle this one.
