### ISSUE TITLE
Implement JoatU Pods

### ISSUE THREAD

**Issue by joatu** [joatuapp/joatu-v2#55]
JoatU pods should be able to be created mutually exclusively. We should be able to invite people to specific pods that would be completely segregated from one another.

For example, if we get a group of people that want to test JoatU in Adelaide Australia, it only makes sense that it wouldn't interfere with the JoatU pod in Montreal.

**Comment by undergroundwebdesigns** [comment]
- [ ] Rename communities -> pods
- [ ] Add a page where admins can create / edit pods.
- [ ] Modify the invitation page so that it invites people into a specific pod, chosen by the inviter.
- [ ] Limit all search functionality to only show results from the searcher's pod.

**Comment by joatu** [comment]
At the same time as all of this, it should be built in a way that offers can eventually overlap pods.  Maybe have a selection in the profile section that allows users to select if their offers are specific to their pod or general to the website. Or if they can create that with each offer. So if you have web design, it's international, but if you have baking cookies, it's only to your city?  Or just to your pod?

Wow, this is complicated.  I think we should keep talking about how we want this to work in the future and the present before you spend too much time building it.

**Comment by undergroundwebdesigns** [comment]
The good news is that we're moving extremely fast right now, so prototyping something out and then changing our minds is completely feasible. That said, limiting search functionality to only allow offers to be shown to their own pod is not a difficult thing, it's about 1 line of code, and just as easy to remove, or make conditional based on just about anything down the road. Heck, I'm tempted to make it an option on a per-offer basis right now (maybe we can do a "default" per-account that can be over-ridden per-offer later... let's stay relatively simple for now.

We also don't really have any concept of a "city" in the system yet (I'm imagining it being a grouping of pods, and maybe there are even serveral "levels" to that?) so let's leave that alone for now, and focus on pods and maybe these "global" offers. As you said, that will be attractive for people who can work remotely (like me ;) )

**Comment by joatu** [comment]
Agreed.

**Comment by undergroundwebdesigns** [comment]
Closing this now, as with the ability to mark offers / requests as local to a pod, all the basic pod functionality is done.
