### ISSUE TITLE
Profile Content

### ISSUE THREAD

**Issue by joatu** [joatuapp/joatu-v2#62]
Currencies: I can see the advantage for having types of currencies already in place (although cheque feels a bit silly to me), but I'm wondering if we want to open it up to tagging and letting people put anything or if it makes more sense like this. Thoughts?  And if we choose like this, we should keep discussing which currencies make the most sense to include.

Requests should be there too so people can see what I'm interested in receiving, especially for direct trades.

**Comment by undergroundwebdesigns** [comment]
Why don't we remove the currencies altogether (for now) and put requests on the profile page instead. This is coming from our recent discussions about promoting trades & focusing less on currencies for transactions. Thoughts @joatu?

**Comment by joatu** [comment]
Sounds like a good idea to me. Either way, we'll be getting a lot of feedback once we launch the alpha.
