### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by joatu** [joatuapp/joatu-v2#65]
The early version can be as simple as giving admin access to edit single lines listing the name of the event, time, place and address.  These would be on the hub homepage.

More complex version can allow organizations to create events and individuals to create events (but they would have to be moderated). These would be public to the initial hub, but could be extended depending on how pods function and how cities function.

**Comment by undergroundwebdesigns** [comment]
Closing this, as a basic version is in place where admins can edit events and place them on the hub / organization pages. More (eg, regular users creating events) can come in another issue.
