### ISSUE TITLE
New User within AlphaPod sent to Uncreated Pod

### ISSUE THREAD

**Issue by joatu** [joatuapp/joatu-v2#77]
Does it matter if there is a space in the postal code?

I have a new person who joined in front of me, but she was sent to an uncreated pod instead of the alphapod. She lives within the alphapod area.

**Comment by undergroundwebdesigns** [comment]
It should not matter if there is a space in the postal code. One thing to consider is that the code looks at the center point of the postal code, as returned by Google, if _that_ is not inside the pod's area, the system won't consider them "within the pod". 

I also re-wrote the code that handles this (converting a postal code to a home-pod) recently. Can you try again with a new (test) user, and let me know if this bug still seems to be happening? If so, can you provide me with postal code you tried so I can try and duplicate it?

**Comment by joatu** [comment]
H2H 2B4 and I'm brought directly into alphapod! I'm not sure how many tests we should try, but it seems so good so far.

**Comment by undergroundwebdesigns** [comment]
Sweet, I'll close this then unless we have other complaints.
