### ISSUE TITLE
Terms link in Footer + Link Color

### ISSUE THREAD

**Issue by joatu** [joatuapp/joatu-v2#83]
- [x] JoatU's Terms & Agreements in the footer
- [x] Please change the color of the link for terms on the password page for increased visibility.

**Comment by undergroundwebdesigns** [comment]
Is there a reason you want the colour of the link for terms changed? It looks just fine to me...

**Comment by joatu** [comment]
Someone said it wasn't visible enough...If we're appealing to all generations, we should make sure everything is as clear as possible.

**Comment by joatu** [comment]
The most contrasting color would be optimal...Oh, and this is on me, but we should have a privacy policy as well.
