### ISSUE TITLE
User in undefined Pod but should be in AlphaPod

### ISSUE THREAD

**Issue by joatu** [joatuapp/joatu-v2#89]
H2J1X3 should have been transfered to alphapod but wasn't.

http://joatu.org/admin/users/6?locale=en

**Comment by undergroundwebdesigns** [comment]
She signed up on the Feb 21st, which I'm pretty sure was before I fixed the assigning to pod code, and there's no way to update your postal code yet.. I'm confused how you expect that they "should have been transferred" to the alpha pod? There's no possible way to do that right now. I agree we need to add it but that's what #79 is all about.

**Comment by joatu** [comment]
I was under the impression that admins could change users postal codes (and
just that users couldn't) and it would put them into the pods by doing so.
My mistake.

**Comment by undergroundwebdesigns** [comment]
Hm.... just looked at it in a bit more detail, I think it _should_ work that way (updating pod / location when an admin changes a postal code too). I'll look into it and get back to you. Either way, fixing it so that both admins and users can change their postal code (and thus pod) is important.
