### ISSUE TITLE
Errors using default installation instructions 

### ISSUE THREAD

**Issue by elavoie** [joatuapp/joatu-v2#93]
I could get to the point where I could start the server with 'foreman start' but got the following trace:

ActiveRecord::StatementInvalid in StaticPageController#home
PG::UndefinedTable: ERROR: relation "users" does not exist LINE 5: WHERE a.attrelid = '"users"'::regclass ^ : SELECT a.attname, format_type(a.atttypid, a.atttypmod), pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod FROM pg_attribute a LEFT JOIN pg_attrdef d ON a.attrelid = d.adrelid AND a.attnum = d.adnum WHERE a.attrelid = '"users"'::regclass AND a.attnum > 0 AND NOT a.attisdropped ORDER BY a.attnum

Extracted source (around line #11):
9
10
11
12
13
14
                
# Naught: https://github.com/avdi/naught
GuestUser = Naught.build do |config|
  config.mimic example: User.new

  def preferences
    # Guest users have a real preferences object, which since guests are never

Rails.root: /Users/erick/Documents/Development/joatu-v2

Application Trace | Framework Trace | Full Trace
activerecord (4.2.0) lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `async_exec'
activerecord (4.2.0) lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `block in exec_no_cache'
activerecord (4.2.0) lib/active_record/connection_adapters/abstract_adapter.rb:466:in `block in log'
activesupport (4.2.0) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activerecord (4.2.0) lib/active_record/connection_adapters/abstract_adapter.rb:460:in `log'
activerecord (4.2.0) lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `exec_no_cache'
activerecord (4.2.0) lib/active_record/connection_adapters/postgresql_adapter.rb:584:in `execute_and_clear'
activerecord (4.2.0) lib/active_record/connection_adapters/postgresql/database_statements.rb:160:in `exec_query'
activerecord (4.2.0) lib/active_record/connection_adapters/postgresql_adapter.rb:733:in `column_definitions'
activerecord-postgis-adapter (3.0.0.beta1) lib/active_record/connection_adapters/postgis_adapter/schema_statements.rb:9:in `columns'
activerecord (4.2.0) lib/active_record/connection_adapters/schema_cache.rb:43:in `columns'
activerecord (4.2.0) lib/active_record/attributes.rb:91:in `columns'
activerecord (4.2.0) lib/active_record/attributes.rb:96:in `columns_hash'
activerecord (4.2.0) lib/active_record/inheritance.rb:205:in `subclass_from_attributes?'
activerecord (4.2.0) lib/active_record/inheritance.rb:54:in `new'
app/models/guest_user.rb:11:in `block in <top (required)>'
/usr/local/lib/ruby/gems/2.1.0/bundler/gems/naught-ee4c8b412e65/lib/naught/null_class_builder.rb:23:in `module_exec'
/usr/local/lib/ruby/gems/2.1.0/bundler/gems/naught-ee4c8b412e65/lib/naught/null_class_builder.rb:23:in `customize'
/usr/local/lib/ruby/gems/2.1.0/bundler/gems/naught-ee4c8b412e65/lib/naught.rb:8:in `build'
app/models/guest_user.rb:10:in `<top (required)>'
activesupport (4.2.0) lib/active_support/dependencies.rb:457:in `load'
activesupport (4.2.0) lib/active_support/dependencies.rb:457:in `block in load_file'
activesupport (4.2.0) lib/active_support/dependencies.rb:647:in `new_constants_in'
activesupport (4.2.0) lib/active_support/dependencies.rb:456:in `load_file'
activesupport (4.2.0) lib/active_support/dependencies.rb:354:in `require_or_load'
activesupport (4.2.0) lib/active_support/dependencies.rb:494:in `load_missing_constant'
activesupport (4.2.0) lib/active_support/dependencies.rb:184:in `const_missing'
activesupport (4.2.0) lib/active_support/dependencies.rb:526:in `load_missing_constant'
activesupport (4.2.0) lib/active_support/dependencies.rb:184:in `const_missing'
app/services/authentication.rb:15:in `initialize'
app/services/authentication.rb:11:in `new'
app/services/authentication.rb:11:in `build'
app/controllers/application_controller.rb:32:in `authentication'
app/controllers/application_controller.rb:60:in `current_user'
app/controllers/application_controller.rb:81:in `set_locale'
activesupport (4.2.0) lib/active_support/callbacks.rb:427:in `block in make_lambda'
activesupport (4.2.0) lib/active_support/callbacks.rb:163:in `call'
activesupport (4.2.0) lib/active_support/callbacks.rb:163:in `block in halting'
activesupport (4.2.0) lib/active_support/callbacks.rb:234:in `call'
activesupport (4.2.0) lib/active_support/callbacks.rb:234:in `block in halting'
activesupport (4.2.0) lib/active_support/callbacks.rb:234:in `call'
activesupport (4.2.0) lib/active_support/callbacks.rb:234:in `block in halting'
activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `call'
activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `call'
activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
activesupport (4.2.0) lib/active_support/callbacks.rb:234:in `call'
activesupport (4.2.0) lib/active_support/callbacks.rb:234:in `block in halting'
activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `call'
activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
activesupport (4.2.0) lib/active_support/callbacks.rb:92:in `call'
activesupport (4.2.0) lib/active_support/callbacks.rb:92:in `_run_callbacks'
activesupport (4.2.0) lib/active_support/callbacks.rb:734:in `_run_process_action_callbacks'
activesupport (4.2.0) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (4.2.0) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (4.2.0) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (4.2.0) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
activesupport (4.2.0) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (4.2.0) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.2.0) lib/active_support/notifications.rb:164:in `instrument'
actionpack (4.2.0) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (4.2.0) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
activerecord (4.2.0) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (4.2.0) lib/abstract_controller/base.rb:137:in `process'
actionview (4.2.0) lib/action_view/rendering.rb:30:in `process'
actionpack (4.2.0) lib/action_controller/metal.rb:195:in `dispatch'
actionpack (4.2.0) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
actionpack (4.2.0) lib/action_controller/metal.rb:236:in `block in action'
actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:73:in `call'
actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:42:in `serve'
actionpack (4.2.0) lib/action_dispatch/journey/router.rb:43:in `block in serve'
actionpack (4.2.0) lib/action_dispatch/journey/router.rb:30:in `each'
actionpack (4.2.0) lib/action_dispatch/journey/router.rb:30:in `serve'
actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:802:in `call'
warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
warden (1.2.3) lib/warden/manager.rb:34:in `catch'
warden (1.2.3) lib/warden/manager.rb:34:in `call'
rack (1.6.0) lib/rack/etag.rb:24:in `call'
rack (1.6.0) lib/rack/conditionalget.rb:25:in `call'
rack (1.6.0) lib/rack/head.rb:13:in `call'
actionpack (4.2.0) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
actionpack (4.2.0) lib/action_dispatch/middleware/flash.rb:260:in `call'
rack (1.6.0) lib/rack/session/abstract/id.rb:225:in `context'
rack (1.6.0) lib/rack/session/abstract/id.rb:220:in `call'
actionpack (4.2.0) lib/action_dispatch/middleware/cookies.rb:560:in `call'
activerecord (4.2.0) lib/active_record/query_cache.rb:36:in `call'
activerecord (4.2.0) lib/active_record/connection_adapters/abstract/connection_pool.rb:647:in `call'
activerecord (4.2.0) lib/active_record/migration.rb:378:in `call'
actionpack (4.2.0) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (4.2.0) lib/active_support/callbacks.rb:88:in `call'
activesupport (4.2.0) lib/active_support/callbacks.rb:88:in `_run_callbacks'
activesupport (4.2.0) lib/active_support/callbacks.rb:734:in `_run_call_callbacks'
activesupport (4.2.0) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (4.2.0) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (4.2.0) lib/action_dispatch/middleware/reloader.rb:73:in `call'
actionpack (4.2.0) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
web-console (2.0.0) lib/action_dispatch/debug_exceptions.rb:18:in `middleware_call'
web-console (2.0.0) lib/action_dispatch/debug_exceptions.rb:13:in `call'
actionpack (4.2.0) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
railties (4.2.0) lib/rails/rack/logger.rb:38:in `call_app'
railties (4.2.0) lib/rails/rack/logger.rb:20:in `block in call'
activesupport (4.2.0) lib/active_support/tagged_logging.rb:68:in `block in tagged'
activesupport (4.2.0) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (4.2.0) lib/active_support/tagged_logging.rb:68:in `tagged'
railties (4.2.0) lib/rails/rack/logger.rb:20:in `call'
actionpack (4.2.0) lib/action_dispatch/middleware/request_id.rb:21:in `call'
rack (1.6.0) lib/rack/methodoverride.rb:22:in `call'
rack (1.6.0) lib/rack/runtime.rb:18:in `call'
activesupport (4.2.0) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
rack (1.6.0) lib/rack/lock.rb:17:in `call'
actionpack (4.2.0) lib/action_dispatch/middleware/static.rb:113:in `call'
rack (1.6.0) lib/rack/sendfile.rb:113:in `call'
railties (4.2.0) lib/rails/engine.rb:518:in `call'
railties (4.2.0) lib/rails/application.rb:164:in `call'
rack (1.6.0) lib/rack/content_length.rb:15:in `call'
puma (2.11.0) lib/puma/server.rb:507:in `handle_request'
puma (2.11.0) lib/puma/server.rb:375:in `process_client'
puma (2.11.0) lib/puma/server.rb:262:in `block in run'
puma (2.11.0) lib/puma/thread_pool.rb:104:in `call'
puma (2.11.0) lib/puma/thread_pool.rb:104:in `block in spawn_thread'

**Comment by undergroundwebdesigns** [comment]
Were you able to run `rake db:setup` as part of step 3 successfully? The error you're seeing is an indication that the users table wasn't created in the database... and step 3 should have either created it or errored out itself.

**Comment by elavoie** [comment]
Here are the first few lines of the db trace I get when I do 'rake 
db:setup'. I guess you are using a database extension 'postgis' which I 
do not have installed.

13:03:11 db.1   | ERROR:  could not open extension control file 
"/usr/local/Cellar/postgresql/9.3.5_1/share/postgresql/extension/postgis.control": 
No such file or directory
13:03:11 db.1   | STATEMENT:  CREATE EXTENSION IF NOT EXISTS postgis
13:03:11 db.1   | ERROR:  could not open extension control file 
"/usr/local/Cellar/postgresql/9.3.5_1/share/postgresql/extension/postgis.control": 
No such file or directory
13:03:11 db.1   | STATEMENT:  CREATE EXTENSION IF NOT EXISTS postgis
13:03:14 db.1   | ERROR:  could not open extension control file 
"/usr/local/Cellar/postgresql/9.3.5_1/share/postgresql/extension/postgis.control": 
No such file or directory
13:03:14 db.1   | STATEMENT:  CREATE EXTENSION IF NOT EXISTS postgis 
WITH SCHEMA public;
13:03:14 db.1   | ERROR:  extension "postgis" does not exist
13:03:14 db.1   | STATEMENT:  COMMENT ON EXTENSION postgis IS 'PostGIS 
geometry, geography, and raster spatial types and functions';
13:03:14 db.1   | ERROR:  type "geometry" does not exist at character 403
[...]

May that be it? If that is the case, 'postgis' should be added to the 
requirements in the readme.

Erick

**Comment by undergroundwebdesigns** [comment]
Yep, you're right. Postgis is required, and will likely have to be installed separately. I'll update the README to reflect that.

**Comment by undergroundwebdesigns** [comment]
@elavoie did that work? Were you able to get the app running locally? If so, can you please close the bug? Thanks!

**Comment by elavoie** [comment]
Yes installing postgis was sufficient to resolve the issue.
