### ISSUE TITLE
Filled out offer but didn't fill out profile breaks site

### ISSUE THREAD

**Issue by joatu** [joatuapp/joatu-v2#95]
http://alpha.joatu.org/en/offers/23

I'm not sure how best to 'fix' this besides that the profile is auto-created as a blank or with silly inoffensive filled in information.

**Comment by undergroundwebdesigns** [comment]
@joatu Need more information... how does it break the site? Screen shots, descriptions of what you did, what you expected to happen, what did happen, all would be great here. Right now you've given me almost 0 useful information, so I have no idea where to even start with this.

It's not such a big deal right now.. everything is pretty simple. I _could_ probably just click around till I discover the problem, but as we progress and errors become more complicated it will be more and more important that bug reports are descriptive.

**Comment by joatu** [comment]
Sorry about that.

I wanted to see someone's offer, but they didn't set up their profile yet (I saw they had no profile icon next to their offer).  I clicked the offer and received this message on the page

"We're sorry, but something went wrong.

If you are the application owner check the logs for more information."

I just wanted to see his offer.

I was guessing that the problem was that he hadn't yet filled out his profile and that is why we couldn't see it (since the offer features a part of the person's profile).

**Comment by joatu** [comment]
http://alpha.joatu.org/en/messages/new?offerer=24

The offer now works, but when I try to send a message to this 'anonymous' offerer, I get an error.

**Comment by undergroundwebdesigns** [comment]
Hm... I can't seem to reproduce this, I was able to successfully send a message to a user who didn't have any profile. Is this still happening to you @joatu? If so, can you give me a more detailed description of how to reproduce it? Thanks!

**Comment by joatu** [comment]
I cannot reproduce this either.  Thanks!
